/**
 * Icon registry.
 *
 * Data files reference icons by string name so content stays free of imports.
 * Icons are imported explicitly (not dynamically) so the bundler can tree-shake
 * everything from lucide-react that this site does not use.
 */
import {
  Atom,
  Award,
  Bell,
  Blocks,
  Boxes,
  Braces,
  Briefcase,
  Bug,
  CalendarCheck,
  Car,
  Check,
  CircleHelp,
  ClipboardList,
  Cloud,
  Code,
  Compass,
  Component,
  Database,
  Download,
  ExternalLink,
  FileCode,
  FileText,
  Flame,
  FlaskConical,
  Fuel,
  Gauge,
  GitBranch,
  Globe,
  GraduationCap,
  Handshake,
  Infinity as InfinityGlyph,
  Layers,
  LayoutDashboard,
  LifeBuoy,
  Lightbulb,
  Mail,
  Map,
  MapPin,
  MessageCircle,
  MessageSquare,
  Monitor,
  MonitorSmartphone,
  Package,
  Palette,
  PenTool,
  Phone,
  Plug,
  Puzzle,
  Radio,
  Rocket,
  Route,
  Search,
  Send,
  Server,
  ShieldCheck,
  ShoppingCart,
  Smartphone,
  Sparkles,
  Table,
  Target,
  Terminal,
  TrendingUp,
  Truck,
  Users,
  Wallet,
  Waypoints,
  Wrench,
  Zap,
} from 'lucide-react'
import { GitHubIcon, LinkedInIcon, WhatsAppIcon } from './BrandIcons.jsx'

const ICONS = {
  atom: Atom,
  award: Award,
  bell: Bell,
  blocks: Blocks,
  boxes: Boxes,
  braces: Braces,
  briefcase: Briefcase,
  bug: Bug,
  'calendar-check': CalendarCheck,
  check: Check,
  car: Car,
  'circle-help': CircleHelp,
  'clipboard-list': ClipboardList,
  cloud: Cloud,
  code: Code,
  compass: Compass,
  component: Component,
  database: Database,
  download: Download,
  'external-link': ExternalLink,
  'file-code': FileCode,
  'file-text': FileText,
  flame: Flame,
  flask: FlaskConical,
  fuel: Fuel,
  gauge: Gauge,
  'git-branch': GitBranch,
  github: GitHubIcon,
  globe: Globe,
  'graduation-cap': GraduationCap,
  handshake: Handshake,
  infinity: InfinityGlyph,
  layers: Layers,
  'layout-dashboard': LayoutDashboard,
  'life-buoy': LifeBuoy,
  lightbulb: Lightbulb,
  linkedin: LinkedInIcon,
  mail: Mail,
  map: Map,
  'map-pin': MapPin,
  'message-circle': MessageCircle,
  'message-square': MessageSquare,
  monitor: Monitor,
  'monitor-smartphone': MonitorSmartphone,
  package: Package,
  palette: Palette,
  'pen-tool': PenTool,
  phone: Phone,
  plug: Plug,
  puzzle: Puzzle,
  radio: Radio,
  rocket: Rocket,
  route: Route,
  search: Search,
  send: Send,
  server: Server,
  shield: ShieldCheck,
  'shopping-cart': ShoppingCart,
  smartphone: Smartphone,
  sparkles: Sparkles,
  table: Table,
  target: Target,
  terminal: Terminal,
  'trending-up': TrendingUp,
  truck: Truck,
  users: Users,
  wallet: Wallet,
  waypoints: Waypoints,
  whatsapp: WhatsAppIcon,
  wrench: Wrench,
  zap: Zap,
}

/**
 * @param {{ name: string, size?: number, className?: string, strokeWidth?: number }} props
 */
export default function Icon({ name, size = 20, strokeWidth = 1.7, ...rest }) {
  const Glyph = ICONS[name] ?? Code
  return <Glyph size={size} strokeWidth={strokeWidth} aria-hidden="true" {...rest} />
}
